### PR TITLE
fixed: AssetManager fails loading when enqueued flash.filesystem.File contains Unicode non-ascii path string.

### PR DESCRIPTION
**Pull request by drumsoft**
AssetManager fails loading when enqueued flash.filesystem.File contains Unicode non-ascii path string.
This patch fixes it.
Additionally, I added AIR version of test suite to certify it.

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Good catch, thanks a lot for the pull request!

I merged the AssetManager fix right away; the new unit test project will have to wait a little longer. It makes a lot of sense to add that, but perhaps I should consider making the unit test AIR-only ... that way, we could test all features and still have only one test.

In any case, thanks! :smile:

**Comment by PrimaryFeather** [comment]
(Labeled 'Feature' for the unit-test part, since the unicode-part is already fixed. :wink:)

**Comment by drumsoft** [comment]
Thanks!

**Comment by PrimaryFeather** [comment]
I'll close this issue for now, since it's not realistic that the 1.x branch of Starling will see those new unit tests. When I update the unit tests, I'll create a separate issue.

**Comment by drumsoft** [comment]
OK. Thank you :)

**Pull request closed without merging**
