### PR TITLE
TextField leading feature

### PR DESCRIPTION
**Pull request by ekeeper**
Author: Leksikov Artem

Hi Daniel! My friend add a leading feature to the TextField class like TextFormat.leading.

### CODE REVIEW

**Comment by LordXaoca** [comment]
vote +1

**Comment by dkruglik** [comment]
+1

**Comment by PrimaryFeather** [comment]
Hell froze over! :volcano: 
I finally added that property. Sorry for the incredibly long delay!

**Comment by randalfien** [comment]
Better late than never! Thanks!

**Comment by dill0wn** [comment]
Thank you!

**Comment by LordXaoca** [comment]
Thank you!

**Comment by itsmeonline** [comment]
Yup. Thanks again here too. Really useful feature.

**Pull request closed without merging**
