### PR TITLE
Added repeat property to FragmentFilter to allow wrapping AGAL shaders.

### PR DESCRIPTION
**Pull request by devon-o**
This is a fix for issue 778 (https://github.com/Gamua/Starling-Framework/issues/778)

### CODE REVIEW

**Comment by neolit123** [comment]
so as the Travis CI build indicates, there seems to be a conflict with the "public get/set repeat()" in DisplacementMapFilter(). i have overlooked that...

"protected function get/set textureRepeat()" paired with "mTextureRepeat" in FragmentFilter might be the non-breaking solution.

**Comment by devon-o** [comment]
Interesting - I overlooked that as well. A 'textureRepeat' property on FragmentFilter may be a quick fix, but DisplacementMapFilter also needs some work as its 'repeat' property is currently broken due to this same issue.

**Comment by PrimaryFeather** [comment]
Thanks a lot for the pull request, and for opening up the issue!

The reason I defaulted to `repeat = false` is that I didn't see any use-case where you'd be able to make use of a wrapping pass texture. As @neolit123 mentioned, the filtered object may have a size of, say, 129x129 pixels, which would create a pass texture with 256x256 pixels (they are always created in POT-style, I think), with only the top left quarter being used. How could you make use of any wrapping with that limitation? 

On the other hand, I probably ran into exactly the same problem with the DisplacementMapFilter, since I added the property there, too. Even though (as you noted) that seems to be broken, :grin:.

So I'd add that property to the FragmentFilter base class and use it in the DisplacementMapFilter, too. Would that work for you?

**Comment by devon-o** [comment]
Hi Daniel,

I considered doing just that (and it would work for my use cases), but ran into another problem. Because the repeat property in DisplacementMapFilter is public, it would be perfectly legit (albeit odd) for a user to change the repeat property from false to true after creating and applying the filter. This is particularly nasty as the mPassTextures vector in FragmentFilter has been filled, so the pass textures won't be (re)created and the filter is left in a broken state at that point. I considered making the repeat property of DisplacementMapFilter protected (or inheriting from the protected FragmentFilter.repeat property I was adding), but that's a potentially app breaking api change for folks currently using the DMFilter. So I left it for now, but I'm open to suggestions (or can give more details in case that didn't make sense).

**Pull request closed without merging**
