### PR TITLE
Added depth test settings to RenderState

### LINKED ISSUE #927: Starling objects should expose depth test parameters
This is very usefull when custom 3D rendering occurres inside display object tree.
Currently starling only calls Context3D.setDepthTest() inside of Painter.nextFrame() with some hardcoded arguments.

I suggest to add "depthWrite" and "depthTest" properties to the DisplayObject and RenderState similarly to "blendMode" property, so depth test state can be automatically set up and restored when necessary.

P. S. I already have almost complete implementation of this feature and will be glad to contribute it, if someone will find this usefull too.

### PR DESCRIPTION
**Pull request by oddwhocanfly**
Closes #927

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Thanks a lot! I will review the code as soon as possible.

**Comment by PrimaryFeather** [comment]
[Add depth test settings to RenderState](https://trello.com/c/ulyfQtjE/1-add-depth-test-settings-to-renderstate)

**Comment by PrimaryFeather** [comment]
It's been a while, but — w00t! I finally merged this into `master`. :bowtie: 
Thanks again for your help! It really makes sense to have it that way.

**Comment by oddwhocanfly** [comment]
Thank you very much! 👍

**Pull request merged**
