### PR TITLE
add Strength property to the filter

### PR DESCRIPTION
**Pull request by aberestovskyi**
Add strength property to the filters like in the native flash filter.

With this property you can make stroke for the text
flash_example

starling_example

var textField:TextField = new TextField(400,200, "Hello World");
textField.format.setTo("DR Agu", 60, 0xFF0000);
textField.x = 50;
textField.y = 50;
textField.filter = new GlowFilter(0x000000, 1, 0.5, 2.5, 1);
addChild(textField);

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Thanks a lot for the pull request, that looks super useful! I'll look into it as soon as time permits.

**Comment by PrimaryFeather** [comment]
I've just made a simpler change that should do the trick, just as well!
If you pull the latest Starling version, you can pass alpha values > 1 to the constructor (or the `alpha` property). Any value above one will raise the "strength".

My recommendation for a nice outline:

```as3
new GlowFilter(0x0, 15, 0.5, 1.0);
```

(Use `resolution = 1` for best results.) Raise the alpha value even higher to make it sharper.

Does that work for you?

**Comment by aberestovskyi** [comment]
Alpha trick doesn't work for me

**Comment by PrimaryFeather** [comment]
Did you pull the very latest version? The change should be equivalent to what you did, actually.
https://github.com/Gamua/Starling-Framework/commit/119b853343f6b0057a5108ccec22365cafe626bc

**Comment by aberestovskyi** [comment]
oh sorry, didn't pull. Yes, with your change it working. But big alpha doesn't good solution as for me. It will be unclear for people.

**Comment by PrimaryFeather** [comment]
Yes, it definitely needs to be documented, that's for sure.

And yes, it might also be useful to add a specific property, like you suggested. But for now, at least we've got a working solution — I'll think about adding that. 👍

**Comment by aberestovskyi** [comment]
Alpha trick doesn't work with not black colors http://c2n.me/3xRPrjr

//alpha trick
new GlowFilter(0x175591, 20, 1, 1);

//new strength property
new GlowFilter(0x175591, 1, 0.5, 14, 1);

**Comment by PrimaryFeather** [comment]
Indeed, that's a good point!

**Comment by sashkooo** [comment]
I think the strength property must be the last, because it will not break existing code which have a resolution property is already set.

**Comment by aberestovskyi** [comment]
I used to native Flash filters for the text befor Starling 2.0. And I set this values befor resolution, because native flash filters has such order. It's easier to switch native flash filters to Starling flash filters. And as for me, filter looks much better with resolution 1.

**Comment by sashkooo** [comment]
for replace native filters yes, but anyway native filters must be reconfigured. Instead, projects that already uses Starling filters will not need any changes. For example, I have in my project already 70 places where Starling filters are used, and 80 places where nativeFilters are used.

**Comment by PrimaryFeather** [comment]
I now fixed the color problem you reported a while ago; with this change, the `alpha` value should act as a valid replacement for `strength`.

Actually, I would have preferred to add a real `strength` parameter — but as you noticed, I would have needed to add this parameter after the `resolution`, i.e. the order would not have been the same as in the classic Flash class. (Changing the order is not an option, because it would break other people's code.)

So, I decided (for now) to keep the order and naming just the same, and just document the additional usage of the `alpha` parameter. In a future version, I might split it up instead — but for now, you've got a working solution.

**Pull request closed without merging**
