### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by honzabrecka**
by updating player version

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Thanks! =)

**Comment by PrimaryFeather** [comment]
Looking good! Now it's passing again. :smile:
Is there always only the very latest version available? Or why exactly does this help?

**Comment by PrimaryFeather** [comment]
Honza, I've been getting errors again recently with (if not all) of the commits to the `v2.0` branch. Could you maybe help me with that?

Here's an exemplary error report:
https://travis-ci.org/Gamua/Starling-Framework/builds/108728292

Thanks a lot in advance!!

**Comment by honzabrecka** [comment]
Hi Daniel, I'll take a look.

Honza

**Pull request merged**
